version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "Dependency Update: "
    assignees:
      - "mrhb787"
    labels:
      - "dependency"
    target-branch: "dev"
